web:
  restart: on-failure
  build: .
  ports:
   - "8000:3000"
  volumes:
   - .:/app
   - ../horseLogs:/app/log
   - ../horseImages:/app/horsifiedImages
  links:
  - redis

redis:
  image: redis:2.6
  ports:
  - "6379:6379"
